name: CI

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  # Run frontend checks
  frontend:
    name: Frontend Tests & Linting
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.CLERK_PUBLISHABLE_KEY }}
      CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
      NEXT_PUBLIC_API_URL: http://localhost:8000

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json

    - name: Cache TypeScript build
      uses: actions/cache@v3
      with:
        path: |
          frontend/.next/cache
          frontend/node_modules/.cache
          frontend/tsconfig.tsbuildinfo
        key: ${{ runner.os }}-typescript-${{ hashFiles('frontend/package-lock.json') }}

    - name: Frontend CI with TypeScript Debug
      working-directory: frontend
      run: |
        echo "=== Installing Dependencies ==="
        npm ci

        echo "=== TypeScript Debug Info ==="
        echo "TypeScript Config:"
        cat tsconfig.json || echo "❌ tsconfig.json not found"
        echo ""
        echo "File Structure (TypeScript files):"
        find . -name "*.ts" -o -name "*.tsx" | head -20
        echo ""
        echo "Module Resolution Configuration:"
        npm run debug-config || echo "❌ Failed to get TypeScript config"
        echo ""

        echo "=== Running Frontend Checks ==="
        echo "Running ESLint..."
        npm run lint
        echo "Running TypeScript type checking..."
        npm run type-check -- --skipLibCheck
        echo "Building application..."
        npm run build

    - name: Upload build artifacts
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: frontend-build
        path: frontend/.next/
        retention-days: 7

  # Check if all required checks pass
  ci-success:
    name: CI Success
    needs: [frontend]
    runs-on: ubuntu-latest
    if: always()

    steps:
    - name: Check CI Status
      run: |
        if [ "${{ needs.frontend.result }}" != "success" ]; then
          echo "❌ CI Failed"
          echo "Frontend: ${{ needs.frontend.result }}"
          exit 1
        else
          echo "✅ All CI checks passed!"
        fi
