name: Dependency Review

on:
  pull_request:
    paths:
      - 'backend/pyproject.toml'
      - 'backend/uv.lock'
      - 'frontend/package.json'
      - 'frontend/package-lock.json'
      - 'frontend/yarn.lock'

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Dependency Review
      uses: actions/dependency-review-action@v4
      with:
        fail-on-severity: moderate

  uv-audit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install uv
      uses: astral-sh/setup-uv@v4

    - name: Check Python dependencies with uv
      working-directory: backend
      run: |
        # Check if dependencies are up to date
        uv sync --frozen
        # List outdated packages
        echo "## Python Dependencies Status" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Checking for outdated packages..." >> $GITHUB_STEP_SUMMARY
        uv pip list --outdated || echo "All packages are up to date" >> $GITHUB_STEP_SUMMARY
      continue-on-error: true

  npm-audit:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18.x'

    - name: Run npm audit
      working-directory: frontend
      run: |
        npm audit --production || true

    - name: Generate audit report
      working-directory: frontend
      run: |
        npm audit --json > audit-report.json || true
        echo "## NPM Audit Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        if [ -s audit-report.json ]; then
          echo "Found $(jq '.metadata.vulnerabilities.total' audit-report.json) vulnerabilities" >> $GITHUB_STEP_SUMMARY
          echo "- Critical: $(jq '.metadata.vulnerabilities.critical' audit-report.json)" >> $GITHUB_STEP_SUMMARY
          echo "- High: $(jq '.metadata.vulnerabilities.high' audit-report.json)" >> $GITHUB_STEP_SUMMARY
          echo "- Moderate: $(jq '.metadata.vulnerabilities.moderate' audit-report.json)" >> $GITHUB_STEP_SUMMARY
          echo "- Low: $(jq '.metadata.vulnerabilities.low' audit-report.json)" >> $GITHUB_STEP_SUMMARY
        else
          echo "✅ No vulnerabilities found" >> $GITHUB_STEP_SUMMARY
        fi
